export interface LapRecord {
  driver: string;
  time: string;
  year: number;
}

export interface CircuitStats {
  lengthKm: number;
  laps: number;
  turns: number;
  topSpeedKmph: number;
  elevationM: number;
  drsZones?: number;
  circuitType?: 'permanent' | 'street' | 'hybrid';
  lapRecord?: LapRecord;
  image3d?: string;
}

const CIRCUIT_STATS: Record<string, CircuitStats> = {
  'Circuit Gilles Villeneuve': {
    lengthKm: 4.361,
    laps: 70,
    turns: 14,
    topSpeedKmph: 342.7,
    elevationM: 5.25,
    drsZones: 3,
    circuitType: 'hybrid',
    lapRecord: { driver: 'V. Bottas', time: '1:13.078', year: 2019 },
    image3d: '/circuits/montreal.jpg',
  },
  'Circuit de Monaco': {
    lengthKm: 3.337,
    laps: 78,
    turns: 19,
    topSpeedKmph: 289.0,
    elevationM: 41.95,
    drsZones: 1,
    circuitType: 'street',
    lapRecord: { driver: 'L. Hamilton', time: '1:12.909', year: 2021 },
    image3d: '/circuits/monaco.jpg',
  },
  'Circuit de Barcelona-Catalunya': {
    lengthKm: 4.657,
    laps: 66,
    turns: 14,
    topSpeedKmph: 307.2,
    elevationM: 29.63,
    drsZones: 2,
    circuitType: 'permanent',
    lapRecord: { driver: 'M. Verstappen', time: '1:18.149', year: 2021 },
    image3d: '/circuits/barcelona.jpg',
  },
  'Red Bull Ring': {
    lengthKm: 4.318,
    laps: 71,
    turns: 10,
    topSpeedKmph: 324.7,
    elevationM: 65.0,
    drsZones: 3,
    circuitType: 'permanent',
    lapRecord: { driver: 'C. Sainz', time: '1:05.619', year: 2020 },
    image3d: '/circuits/red-bull-ring.jpg',
  },
  'Silverstone Circuit': {
    lengthKm: 5.891,
    laps: 52,
    turns: 18,
    topSpeedKmph: 332.6,
    elevationM: 11.31,
    drsZones: 2,
    circuitType: 'permanent',
    lapRecord: { driver: 'M. Verstappen', time: '1:27.097', year: 2020 },
    image3d: '/circuits/silverstone.jpg',
  },
  'Bahrain International Circuit': {
    lengthKm: 5.412,
    laps: 57,
    turns: 15,
    topSpeedKmph: 322.0,
    elevationM: 11.0,
    drsZones: 3,
    circuitType: 'permanent',
    lapRecord: { driver: 'P. de la Rosa', time: '1:31.447', year: 2005 },
  },
  'Jeddah Corniche Circuit': {
    lengthKm: 6.174,
    laps: 50,
    turns: 27,
    topSpeedKmph: 322.0,
    elevationM: 12.0,
    drsZones: 3,
    circuitType: 'street',
  },
  'Albert Park Circuit': {
    lengthKm: 5.278,
    laps: 58,
    turns: 14,
    topSpeedKmph: 330.0,
    elevationM: 2.0,
    drsZones: 4,
    circuitType: 'hybrid',
    lapRecord: { driver: 'C. Leclerc', time: '1:20.260', year: 2022 },
    image3d: '/circuits/albert-park.jpg',
  },
  'Suzuka International Racing Course': {
    lengthKm: 5.807,
    laps: 53,
    turns: 18,
    topSpeedKmph: 338.0,
    elevationM: 40.0,
    drsZones: 2,
    circuitType: 'permanent',
    lapRecord: { driver: 'L. Hamilton', time: '1:30.983', year: 2019 },
    image3d: '/circuits/suzuka.jpg',
  },
  'Shanghai International Circuit': {
    lengthKm: 5.451,
    laps: 56,
    turns: 16,
    topSpeedKmph: 331.0,
    elevationM: 7.0,
    drsZones: 3,
    circuitType: 'permanent',
    lapRecord: { driver: 'M. Schumacher', time: '1:32.238', year: 2004 },
    image3d: '/circuits/shanghai.jpg',
  },
  'Miami International Autodrome': {
    lengthKm: 5.412,
    laps: 57,
    turns: 19,
    topSpeedKmph: 338.0,
    elevationM: 2.0,
    drsZones: 3,
    circuitType: 'hybrid',
    image3d: '/circuits/miami.jpg',
  },
  'Circuit de Spa-Francorchamps': {
    lengthKm: 7.004,
    laps: 44,
    turns: 19,
    topSpeedKmph: 345.0,
    elevationM: 104.0,
    drsZones: 2,
    circuitType: 'permanent',
    lapRecord: { driver: 'V. Bottas', time: '1:46.286', year: 2018 },
    image3d: '/circuits/spa.jpg',
  },
  'Circuit Zandvoort': {
    lengthKm: 4.259,
    laps: 72,
    turns: 14,
    topSpeedKmph: 314.0,
    elevationM: 9.0,
    drsZones: 2,
    circuitType: 'permanent',
    image3d: '/circuits/zandvoort.jpg',
  },
  'Autodromo Nazionale Monza': {
    lengthKm: 5.793,
    laps: 53,
    turns: 11,
    topSpeedKmph: 362.0,
    elevationM: 11.0,
    drsZones: 2,
    circuitType: 'permanent',
    lapRecord: { driver: 'R. Barrichello', time: '1:21.046', year: 2004 },
    image3d: '/circuits/monza.jpg',
  },
  'Marina Bay Street Circuit': {
    lengthKm: 4.94,
    laps: 62,
    turns: 19,
    topSpeedKmph: 322.0,
    elevationM: 5.0,
    drsZones: 3,
    circuitType: 'street',
    image3d: '/circuits/singapore.jpg',
  },
  'Hungaroring': {
    lengthKm: 4.381,
    laps: 70,
    turns: 14,
    topSpeedKmph: 315.0,
    elevationM: 36.0,
    drsZones: 2,
    circuitType: 'permanent',
    lapRecord: { driver: 'L. Hamilton', time: '1:16.627', year: 2020 },
    image3d: '/circuits/hungaroring.jpg',
  },
  'Baku City Circuit': {
    lengthKm: 6.003,
    laps: 51,
    turns: 20,
    topSpeedKmph: 348.0,
    elevationM: 12.0,
    drsZones: 2,
    circuitType: 'street',
    lapRecord: { driver: 'C. Leclerc', time: '1:43.009', year: 2019 },
    image3d: '/circuits/baku.jpg',
  },
  'Circuit de la Sarthe': {
    lengthKm: 13.626,
    laps: 0,
    turns: 38,
    topSpeedKmph: 370.0,
    elevationM: 31.0,
    circuitType: 'hybrid',
  },
  'Interlagos': {
    lengthKm: 4.309,
    laps: 71,
    turns: 15,
    topSpeedKmph: 335.0,
    elevationM: 40.0,
    drsZones: 2,
    circuitType: 'permanent',
    lapRecord: { driver: 'V. Bottas', time: '1:10.540', year: 2018 },
    image3d: '/circuits/interlagos.jpg',
  },
  'Yas Marina Circuit': {
    lengthKm: 5.281,
    laps: 58,
    turns: 16,
    topSpeedKmph: 335.0,
    elevationM: 5.0,
    drsZones: 2,
    circuitType: 'permanent',
    lapRecord: { driver: 'M. Verstappen', time: '1:26.103', year: 2021 },
    image3d: '/circuits/yas-marina.jpg',
  },
  'Circuit of the Americas': {
    lengthKm: 5.513,
    laps: 56,
    turns: 20,
    topSpeedKmph: 344.7,
    elevationM: 30.9,
    drsZones: 3,
    circuitType: 'permanent',
    lapRecord: { driver: 'C. Leclerc', time: '1:36.169', year: 2019 },
    image3d: '/circuits/cota.jpg',
  },
  'Autodromo Hermanos Rodriguez': {
    lengthKm: 4.304,
    laps: 71,
    turns: 17,
    topSpeedKmph: 350.0,
    elevationM: 8.0,
    drsZones: 3,
    circuitType: 'permanent',
    lapRecord: { driver: 'V. Bottas', time: '1:18.741', year: 2021 },
    image3d: '/circuits/mexico.jpg',
  },
  'Las Vegas Strip Circuit': {
    lengthKm: 6.201,
    laps: 50,
    turns: 17,
    topSpeedKmph: 342.0,
    elevationM: 2.0,
    drsZones: 2,
    circuitType: 'street',
    image3d: '/circuits/las-vegas.jpg',
  },
  'Losail International Circuit': {
    lengthKm: 5.419,
    laps: 57,
    turns: 16,
    topSpeedKmph: 338.0,
    elevationM: 5.0,
    drsZones: 2,
    circuitType: 'permanent',
    image3d: '/circuits/qatar.jpg',
  },
  'Circuito de Madrid': {
    lengthKm: 5.473,
    laps: 66,
    turns: 20,
    topSpeedKmph: 330.0,
    elevationM: 20.0,
    drsZones: 3,
    circuitType: 'hybrid',
    image3d: '/circuits/madrid.jpg',
  },
  'Imola': {
    lengthKm: 4.909,
    laps: 63,
    turns: 19,
    topSpeedKmph: 326.0,
    elevationM: 33.0,
    drsZones: 2,
    circuitType: 'permanent',
    lapRecord: { driver: 'L. Hamilton', time: '1:15.484', year: 2020 },
  },
  'Nürburgring Nordschleife': {
    lengthKm: 20.832,
    laps: 0,
    turns: 170,
    topSpeedKmph: 300.0,
    elevationM: 300.0,
  },
  'Nürburgring GP': {
    lengthKm: 5.148,
    laps: 60,
    turns: 15,
    topSpeedKmph: 310.0,
    elevationM: 56.0,
  },
  'Dekra Lausitzring': {
    lengthKm: 3.478,
    laps: 34,
    turns: 12,
    topSpeedKmph: 270.0,
    elevationM: 5.0,
  },
  'Daytona International Speedway': {
    lengthKm: 5.73,
    laps: 0,
    turns: 12,
    topSpeedKmph: 330.0,
    elevationM: 10.0,
  },
  'Sebring International Raceway': {
    lengthKm: 6.02,
    laps: 0,
    turns: 17,
    topSpeedKmph: 310.0,
    elevationM: 6.0,
  },
  'Watkins Glen International': {
    lengthKm: 5.43,
    laps: 0,
    turns: 11,
    topSpeedKmph: 315.0,
    elevationM: 54.0,
  },
  'Misano World Circuit': {
    lengthKm: 4.226,
    laps: 28,
    turns: 16,
    topSpeedKmph: 290.0,
    elevationM: 10.0,
  },
  'TT Circuit Assen': {
    lengthKm: 4.542,
    laps: 26,
    turns: 18,
    topSpeedKmph: 310.0,
    elevationM: 5.0,
  },
  'Brno Circuit': {
    lengthKm: 5.403,
    laps: 21,
    turns: 14,
    topSpeedKmph: 320.0,
    elevationM: 73.0,
  },
  'Balaton Park Circuit': {
    lengthKm: 4.074,
    laps: 22,
    turns: 14,
    topSpeedKmph: 290.0,
    elevationM: 15.0,
  },
  'Toyota': {
    lengthKm: 3.483,
    laps: 0,
    turns: 10,
    topSpeedKmph: 160.0,
    elevationM: 30.0,
  },
  'Loutraki': {
    lengthKm: 18.3,
    laps: 0,
    turns: 0,
    topSpeedKmph: 180.0,
    elevationM: 600.0,
  },
  'Tartu': {
    lengthKm: 15.8,
    laps: 0,
    turns: 0,
    topSpeedKmph: 180.0,
    elevationM: 40.0,
  },
};

/**
 * Maps alternate circuit names used in the calendar to canonical keys in CIRCUIT_STATS.
 * Covers name differences between data sources (FIA names, local names, typos).
 */
const CIRCUIT_ALIASES: Record<string, string> = {
  'Suzuka Circuit': 'Suzuka International Racing Course',
  'Monza Circuit': 'Autodromo Nazionale Monza',
  'Interlagos Circuit': 'Interlagos',
  'Imola Circuit': 'Imola',
  'Autódromo Hermanos Rodríguez': 'Autodromo Hermanos Rodriguez',
  'Lusail International Circuit': 'Losail International Circuit',
  'Madring Street Circuit': 'Circuito de Madrid',
  'Nürburgring': 'Nürburgring GP',
};

export function getCircuitStats(circuitName: string): CircuitStats | undefined {
  // Direct match
  if (CIRCUIT_STATS[circuitName]) return CIRCUIT_STATS[circuitName];

  // Alias match
  const alias = CIRCUIT_ALIASES[circuitName];
  if (alias && CIRCUIT_STATS[alias]) return CIRCUIT_STATS[alias];

  // Fuzzy match — partial name containment
  for (const [key, value] of Object.entries(CIRCUIT_STATS)) {
    if (circuitName.includes(key) || key.includes(circuitName)) return value;
  }
  return undefined;
}
