/** Maps full driver names (as shown in results) → Jolpica driverRef */
export const F1_DRIVER_REFS_FULL: Record<string, string> = {
  'Max Verstappen': 'max_verstappen',
  'Lewis Hamilton': 'hamilton',
  'Charles Leclerc': 'leclerc',
  'Lando Norris': 'norris',
  'Oscar Piastri': 'piastri',
  'George Russell': 'russell',
  'Andrea Kimi Antonelli': 'antonelli',
  'Kimi Antonelli': 'antonelli',
  'Fernando Alonso': 'alonso',
  'Lance Stroll': 'stroll',
  'Pierre Gasly': 'gasly',
  'Esteban Ocon': 'ocon',
  'Oliver Bearman': 'bearman',
  'Nico Hulkenberg': 'hulkenberg',
  'Carlos Sainz': 'carlos_sainz',
  'Franco Colapinto': 'colapinto',
  'Yuki Tsunoda': 'tsunoda',
  'Isack Hadjar': 'hadjar',
  'Gabriel Bortoleto': 'bortoleto',
  'Jack Doohan': 'doohan',
  'Liam Lawson': 'lawson',
};

/** Maps abbreviated driver names (as shown in standings) → Jolpica driverRef */
export const F1_DRIVER_REFS: Record<string, string> = {
  'G. Russell':    'russell',
  'K. Antonelli':  'antonelli',
  'C. Leclerc':    'leclerc',
  'L. Hamilton':   'hamilton',
  'L. Norris':     'norris',
  'O. Piastri':    'piastri',
  'M. Verstappen': 'max_verstappen',
  'L. Lawson':     'lawson',
  'F. Alonso':     'alonso',
  'L. Stroll':     'stroll',
  'P. Gasly':      'gasly',
  'E. Ocon':       'ocon',
  'O. Bearman':    'bearman',
  'N. Hulkenberg': 'hulkenberg',
  'C. Sainz':      'carlos_sainz',
  'O. Colapinto':  'colapinto',
  'Y. Tsunoda':    'tsunoda',
  'C. Hadjar':     'hadjar',
  'G. Bortoleto':  'bortoleto',
  'J. Doohan':     'doohan',
};
